 <launch>  
<include file="/opt/ros/melodic/share/realsense2_camera/launch/rs_camera.launch"/>
<node pkg="camera" type ="rgb" name="color_stream" output="screen">
      <param name="frame_rate" type="int" value="60" />
      <param name="resolution_height" type="int" value="480" />
      <param name="resolution_width" type="int" value="848" />
  </node> 
   <node pkg="detect_image" type ="detectImage.py" name="detect_image_node" output="screen">
   </node>
</launch>